from enum import StrEnum

from pydantic import BaseModel


class ErrorCode(StrEnum):
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
    API_KEY_NOT_FOUND = "API_KEY_NOT_FOUND"
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
    MEMORY_NOT_FOUND = "MEMORY_NOT_FOUND"
    WORKFLOW_NOT_FOUND = "WORKFLOW_NOT_FOUND"
    CONFLICT_ERROR = "CONFLICT_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RATE_LIMIT_ERROR = "RATE_LIMIT_ERROR"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    QUOTA_UNAVAILABLE = "QUOTA_UNAVAILABLE"
    RAG_UNAVAILABLE = "RAG_UNAVAILABLE"
    KNOWLEDGE_BASE_EMPTY = "KNOWLEDGE_BASE_EMPTY"
    NO_RELEVANT_CONTEXT = "NO_RELEVANT_CONTEXT"
    RAG_STORAGE_UNAVAILABLE = "RAG_STORAGE_UNAVAILABLE"
    RAG_DOCUMENT_INVALID = "RAG_DOCUMENT_INVALID"
    RAG_DOCUMENT_TOO_LARGE = "RAG_DOCUMENT_TOO_LARGE"
    RAG_INGESTION_FAILED = "RAG_INGESTION_FAILED"
    RAG_EMBEDDING_UNAVAILABLE = "RAG_EMBEDDING_UNAVAILABLE"
    RAG_EMBEDDING_FAILED = "RAG_EMBEDDING_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ErrorResponse(BaseModel):
    code: ErrorCode
    message: str
    request_id: str | None = None
    thread_id: str | None = None
