from typing import Protocol, runtime_checkable

from app.auth.models import APIKeyRecord


@runtime_checkable
class APIKeyRepository(Protocol):
    async def find_by_key_hash(self, key_hash: str) -> APIKeyRecord | None: ...

    async def find_by_key_hash_prefix(self, prefix: str) -> list[APIKeyRecord]: ...

    async def list_keys(self) -> list[APIKeyRecord]: ...

    async def create_key(self, record: APIKeyRecord) -> APIKeyRecord: ...

    async def ensure_key(self, record: APIKeyRecord) -> bool:
        """Idempotent upsert. Returns True if created, False if existed."""
        ...

    async def update_status(self, key_hash: str, status: str) -> bool: ...

    async def touch_last_used(self, key_hash: str) -> None: ...
